# Generated by Django 3.2.7 on 2021-10-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='employers',
        ),
    ]
