# Generated by Django 3.2.7 on 2021-10-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20211024_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfile',
            options={'ordering': ('-pk',)},
        ),
    ]
