# Generated by Django 3.2.7 on 2021-10-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_alter_companyfile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
