# Generated by Django 3.2.7 on 2021-10-27 23:24

import api.employers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_alter_employer_company_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='logo',
        ),
        migrations.AddField(
            model_name='employer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.employers.models.employer_upload_file),
        ),
    ]
