# Generated by Django 3.2.7 on 2021-10-27 23:42

import api.employers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_auto_20211027_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='image',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.employers.models.company_file_upload_file),
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to=api.employers.models.company_file_upload_file),
        ),
    ]
