# Generated by Django 3.2.7 on 2021-10-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_auto_20211027_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
