# Generated by Django 3.2.7 on 2021-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Disable', 'disable'), ('Active', 'active')], default=('Disable', 'disable'), max_length=100),
        ),
    ]
