# Generated by Django 3.2.7 on 2021-12-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id_temp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
