# Generated by Django 3.2.7 on 2021-10-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='remember_token',
            new_name='token',
        ),
    ]
