# Generated by Django 3.2.7 on 2021-10-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_remember_token_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',)},
        ),
    ]
