# Generated by Django 3.2.7 on 2021-12-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(blank=True, max_length=20, null=True)),
                ('iso_3166_1', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Trailer', 'Trailer'), ('Teaser', 'Teaser')], max_length=100, null=True)),
                ('official', models.BooleanField(blank=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('id_temp', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos_products', to='products.product')),
            ],
            options={
                'db_table': 'videos',
                'ordering': ('-pk',),
            },
        ),
    ]
