# Generated by Django 3.2.7 on 2021-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211217_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
