# Generated by Django 3.2.7 on 2021-10-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-pk',)},
        ),
    ]
