# Generated by Django 3.2.7 on 2021-10-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211024_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='curency',
            field=models.CharField(blank=True, choices=[('VND', 'vnd'), ('$', 'dollar')], default=('VND', 'vnd'), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='package_type',
            field=models.CharField(blank=True, choices=[('Free', 'free'), ('Basic', 'basic'), ('Advance', 'advance')], default=('Free', 'free'), max_length=255, null=True),
        ),
    ]
