# Generated by Django 3.2.7 on 2021-10-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211024_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='curency',
            new_name='currency',
        ),
    ]
