# Generated by Django 3.2.7 on 2021-10-27 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_auto_20211027_2324'),
        ('jobs', '0004_rename_curency_job_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employer'),
        ),
    ]
