# Generated by Django 3.2.7 on 2021-10-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True, choices=[('VND', 'vnd'), ('USD', 'dollar')], default=('VND', 'vnd'), max_length=100, null=True),
        ),
    ]
