# Generated by Django 3.2.7 on 2021-10-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
