# Generated by Django 3.2.7 on 2021-10-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_company_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_location',
            field=models.CharField(blank=True, choices=[('VND', 'vnd'), ('USD', 'dollar')], default=('Tất Cả Địa Điểm', 'tat ca dia diem'), max_length=100, null=True),
        ),
    ]
