# Generated by Django 3.2.7 on 2021-10-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_location',
            field=models.CharField(blank=True, choices=[('Tất Cả Địa Điểm', 'tat ca dia diem'), ('Đà Nẵng', 'da nang'), ('Hà Nội', 'ha noi'), ('Tp. Hồ Chí Minh', 'ho chi minh'), ('Quảng Nam', 'quang nam')], default=('Tất Cả Địa Điểm', 'tat ca dia diem'), max_length=100, null=True),
        ),
    ]
